/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Homepage: typeof import('./../components/Homepage.vue')['default']
    ImageContrast: typeof import('./../components/ImageContrast.vue')['default']
    Login: typeof import('./../components/Login.vue')['default']
    Map: typeof import('./../components/Map.vue')['default']
    Menu: typeof import('./../components/Menu.vue')['default']
    NewImage: typeof import('./../components/NewImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegmentEdit: typeof import('./../components/SegmentEdit.vue')['default']
    Signup: typeof import('./../components/Signup.vue')['default']
  }
}
